### ISSUE TITLE
Missing information about mandatory constraints

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-mpls-yang/te#18]
PCEP offers the possibility to decide whether a constraint (almost any object actually in PCEP) must be considered by the path computation or may be ignored.

" P flag (Processing-Rule - 1-bit): the P flag allows a PCC to specify
in a PCReq message sent to a PCE whether the object must be taken
into account by the PCE during path computation or is just
optional. When the P flag is set, the object MUST be taken into
account by the PCE. Conversely, when the P flag is cleared, the
object is optional and the PCE is free to ignore it.

I flag (Ignore - 1 bit): the I flag is used by a PCE in a PCRep
message to indicate to a PCC whether or not an optional object was
processed. The PCE MAY include the ignored optional object in its
reply and set the I flag to indicate that the optional object was
ignored during path computation. When the I flag is cleared, the
PCE indicates that the optional object was processed during the
path computation. The setting of the I flag for optional objects
is purely indicative and optional. The I flag has no meaning in a
PCRep message when the P flag has been set in the corresponding
PCReq message."

As shown in the text above (from RFC5440), in case an optional object is not managed by the PCE, it's possible to return this fact in the response.
The proposal is to include a mechanism like that also in the path computation YANG model, at least inside the generic-path-constraints grouping adding a boolean leaf to specify whether the constraint is mandatory or not. The additional leaf could be added to path-metrics-bound_config, generic-path-affinities and generic-path-srlgs.

In addition to that, in order to introduce also the function of the I flag, it's also possible to add another Boolean leaf to specify whether the constraint has been ignored, in case the mandatory leaf is set to false (if a path having a constraint with mandatory leaf true cannot honor or manage the constraint, it should return an error instead).

This would add a powerful feature to the path computation; in any case, if this proposal is not introduced in the YANG, it's needed to clarify the behavior of the path computation in case a constraint cannot be honored: failure ? the best path satisfying the other constraints if any, and with or without indication of the violation ?

Carlo, Francesco, Italo and Sergio

**Comment by ietf-mpls-yang** [comment]
Need to investigate use of meta-data with YANG model node
AI (Xufeng): will share example
AI (Xufeng): will send email to check with YANG Drs.

**Comment by efralaz** [comment]
An use case for the usage of optionality in constraints. Suppose to have an optical network like this one:
![net1](https://user-images.githubusercontent.com/1518199/35729952-43214746-0808-11e8-9352-d6b84a6a4f13.PNG)
The red path is deployed and protected by a restoration. When a fault occur we only know that the traffic get lost, but we don't know (yet) where the fault is, and we want to reroute the path quickly reusing as much as possible the original path (to limit re-leveling all the optical spans). 
Asking for a path computation between A and D having a non-mandatory include-resources constraint A-B-C-D solves the issue, as the path computation element will look for a feasible path with a minimum violation of the requested constraint. 
![net2](https://user-images.githubusercontent.com/1518199/35730185-0527919c-0809-11e8-9761-ec9842157500.PNG)
There is NO WAY to do so with the cascade of named-path-constraints defined so far. 
Further issue with the named-path-constraints list is that it's indexed by name (a string) so suitable names for the constraints should be chosen in order to guarantee the wanted order/priority. Some questions arise then : the constraints must be saved in some data store or this is just optional (in this case the name is just used to sort the list and discarded I suppose) ? 
Is it possible just to use the name to recall a stored constraint ? So I can call constraints "Joe", "William", "Sergio" and "Francesco". 
But in this we cannot guarantee that naming is appropriate for the priority we want to give to the used constraint ? So we'll be redefining constraints in this case ?

**Comment by ietf-mpls-yang** [comment]
this issue was closed by adding the optimize-include/exclude in the model
